services:
  db:
    image: postgres:16
    container_name: fitnexus-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - fitness-data:/var/lib/postgresql/data
volumes:
  fitness-data: